apiVersion: v1
kind: Pod
metadata:
  name: my-pod
spec:
  initContainers:
  - name: init-container
    image: busybox
    command: ["/bin/sh", "-c", "echo 'Running...' && sleep 60"]
  containers:
  - name: actual-container
    image: nginx
    command: ["/bin/sh", "-c", "echo 'Initalized after 60 seconds ..'"]