apiVersion: apps/v1
kind: Deployment
metadata:
  name: multi-container-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      app: multi-container
  template:
    metadata:
      labels:
        app: multi-container
    spec:
      containers:
      - name: web-container
        image: nginx:latest
        ports:
        - containerPort: 80
      - name: worker-container
        image: busybox:latest
        command: ["/bin/sh", "-c", "echo The worker container is running && sleep 3600"]
