apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: orangehrm-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
spec:
  rules:
  - host: example.com
    http:
      paths:
      - path: /orangehrm
        pathType: Prefix
        backend:
          service:
            name: orangehrm
            port:
              name: http
