version: '3'
services:
  jenkins:
    image: jenkins/jenkins:lts
    ports:
      - "8686:8080"
      - "50000:50000"
    volumes:
      - jenkins_hometech:/var/jenkins_home
      - /var/run/docker.sock:/var/run/docker.sock
volumes:
  jenkins_hometech:
