version: '3'
services:
  studentfrontend:
    image: student-frontend
    ports:
      - 7000:80
  studentbackend:
    image: student-backend
    ports:
      - 5000:5000
    depends_on:
      - db
  db:
    image: mongo
    ports:
      - 27017:27017
    environment:
      MYSQL_DATABASE: orangehrm
      MYSQL_USER: orangehrm
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: password
    volumes:
      - orangehrm-db:/var/lib/mysql

volumes:
  orangehrm-db: